/**
 * A stored B2B registration request.
 */
export interface B2BRequest {
  id: string;
  companyName: string;
  contact: string;
  message: string;
  createdAt: string;
}

/**
 * The fields required to create a new B2B request.
 * `id` and `createdAt` are generated by the repository.
 */
export type NewB2BRequest = Omit<B2BRequest, "id" | "createdAt">;

/**
 * Contract for B2B request data access.
 */
export interface B2BRepository {
  /** Persist a new B2B request and return the stored record. */
  create(request: NewB2BRequest): Promise<B2BRequest>;

  /** Retrieve all B2B requests, newest first. */
  findAll(): Promise<B2BRequest[]>;

  /** Find a single B2B request by id, or null if it doesn't exist. */
  findById(id: string): Promise<B2BRequest | null>;
}
